plugin: aws_ec2
boto_profile: default
regions:
  - ap-south-1
filters:
  # All instances with their `Environment` tag set to `dev`
  tag:env:
    - dev
    - prod 

keyed_groups:
  - key: tags.Role
    separator: ""

compose:
  ansible_host: private_ip_address   
    
