- name: Provision Ubuntu & Amazon Linux EC2 Instances
  hosts: localhost
  tasks:
  - name: Provision Ubuntu EC2 Instances
    amazon.aws.ec2:
      key_name: mumbai-key
      region: ap-south-1
      instance_type: t2.micro
      image: ami-0851b76e8b1bce90b
      wait: yes
      wait_timeout: 500
      count: 1
      instance_tags:
        ubuntu: webserver
      monitoring: yes
      group_id: sg-05bc8adcf00d08f5e
      vpc_subnet_id: subnet-0d1003b6d85c91568
      assign_public_ip: yes
    tags: ubuntu

  - name: Provision Amazon Linux EC2 Instances
    amazon.aws.ec2:
      key_name: mumbai-key
      region: ap-south-1
      instance_type: t2.micro
      image: ami-0a3277ffce9146b74
      wait: yes
      wait_timeout: 500
      count: 1
      instance_tags:
        amazon-linux: webserver
      monitoring: yes
      group_id: sg-05bc8adcf00d08f5e
      vpc_subnet_id: subnet-0d1003b6d85c91568
      assign_public_ip: yes
    tags: amazon-linux

