- hosts: localhost
  become: yes
  tasks:
  - name: Pause play until a URL is reachable from this host
    uri:
      url: "https://jsonplaceholder.typicode.com/todos/1"
      follow_redirects: none
      method: GET
    register: _result
    until: _result.status == 200
    retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
    delay: 5
  
  - name: Display the Result
    debug:
      msg: "{{ _result }}"